name: Azure App Service

on:
  workflow_dispatch:  # Allow manual triggering from GitHub UI
  push:
    branches:
      - master  # Runs when code is pushed to master branch

env:
  AZURE_WEBAPP_NAME: AzureAppServiceLearning
  DOTNET_VERSION: '8.x'
  SOLUTION_PATH: 'AzureApp.sln'
  API_PROJECT_PATH: 'AzureApp'
  PUBLISH_DIR: './publish'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: |
          dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: |
          dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build -p:PublishDir=${{ env.PUBLISH_DIR }}

      # Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.PUBLISH_DIR }}'
